version: '3.8'
services:
  server:
    image: public.ecr.aws/g7l7f1t5/liquibase-gen-back:latest
    ports:
      - 9000:9000

  client:
    image: public.ecr.aws/g7l7f1t5/liquibase-gen-front:latest
    ports:
      - 8080:8080
    depends_on:
      - server